apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ad-service-ingress
  namespace: ads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ad.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ad-service
            port:
              number: 80
