apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
  namespace: ads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
      - name: ad-service
        image: nginx:alpine
        ports:
        - containerPort: 80
